database:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
certificate_authority:
  passphrase: the ultimate secret!
  subject:
    C: US
    ST: California
    L: Santa Barbara
    O: example.com
    OU: Engineering
  email: licensing@example.com
  expiry_seconds: 3.15569e+8 # 10 years in seconds
  serial: 1
  version: 2 # this means version 3--X.509 certificate versions are 0-indexed. >_<
